### ISSUE TITLE
Code hasn't been released in a while.

### ISSUE THREAD

**Issue by markww** [jmillikin/rules_flex#7]
Hi all, this code hasn't been released in a while. I'm wondering if you'd be willing to cut a 0.3 release. I'm particularly interested in using the `flex_register_toolchains(extra_copts=...)` option, but it's more complicated (and sketchy) to target a non-release with `bazel`'s `http_archive` rule. Thanks!

**Comment by jmillikin** [comment]
Due to some pandemic-related things I don't have any time available for maintenance of personal projects, and I expect this state to continue for at least another 2-3 months.

For now, is it feasible for you to use either (1) `http_repository` with Github's auto-generated archives or (2) `git_repository` with the commit at current HEAD?

**Comment by markww** [comment]
That’s totally doable, not a problem.
